---
- hosts: openstack_instances
  connection: local
  gather_facts: false
  roles:
    - openstack_instances

- hosts: openstack_instances
  become: yes
  tasks: 
    - name: remove previous hostname ip binding 
      lineinfile:
        dest: /etc/hosts
        regexp: '^10.2.'
        state: absent 
    - name: configure /etc/hosts files
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ inventory_hostname }}$'
        line: "{{ ansible_ssh_host }} {{ inventory_hostname }}"
        state: present
    - name: configure /etc/ntp.conf
      lineinfile:
        dest: /etc/ntp.conf
        regexp: '^server 10.2.1.14'
        line: 'server 10.2.1.18 prefer iburst'
        state: present
    - name: reboot ntp service
      service: 
        name: ntp
        state: restarted
