---
- name: add webupd8 ppa to repository
  apt_repository: repo='ppa:webupd8team/java' state=present update_cache=yes

- name: accept oracle license file 
  debconf: 
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'

- name: install jdk-8
  apt: name=oracle-java8-installer state=present

- name: set $JAVA_HOME
  lineinfile:
    state: present
    dest: /home/ubuntu/.profile
    line: 'export JAVA_HOME={{ java_home }}'
    insertafter: 'EOF'
    regexp: 'export JAVA_HOME={{ java_home }}'

- name: set $PATH 
  lineinfile:
    state: present
    dest: /home/ubuntu/.profile
    line: 'export PATH=$PATH:$JAVA_HOME/bin'
    insertafter: 'EOF'
    regexp: 'export PATH=\$PATH:\$JAVA_HOME/bin'

- name: source profile 
  shell: . /home/ubuntu/.profile
