---
- hosts: openstack_instances
  connection: local
  tasks:
    - name: gather facts
      os_server_facts:
        server: "{{ inventory_hostname }}"
      register: res
    - name: set ansible_ssh_host 
      set_fact: ansible_ssh_host={{ res['ansible_facts']['openstack_servers'][0]['private_v4'] }}
